### ISSUE TITLE
Standard plot function for mzID objects

### ISSUE THREAD

**Issue by thomasp85** [thomasp85/mzID#14]
I would like to have a graphical display of mzID objects, but would like suggestion as to which should be the default one...

Some ideas:
- Score distribution plot for decoy vs. real database (problematic as not all mzID objects are based on TDA approach and the score  name varies between search engines)
- Some sort of coverage vs. score scatterplot

place add suggestions...

**Comment by lgatto** [comment]
Closing, as very unlikely to get ever implemented.
