### ISSUE TITLE
export `mzID` and `mzIDCollection` classes

### ISSUE THREAD

**Issue by sgibb** [thomasp85/mzID#26]
Dear Thomas,

I want to create a class union to handle `mzID` objects but it seems that no mzID class is exported.

```r
library("mzID")
packageVersion("mzID")
[1] ‘1.4.1’
setClassUnion("mzIDClasses", members = c("mzID", "mzIDCollection"))
Warning messages:
1: class "mzID" is defined (with package slot ‘mzID’) but no metadata object found to revise superClass information---not exported?  Making a copy in package ‘.GlobalEnv’ 
2: class "mzIDCollection" is defined (with package slot ‘mzID’) but no metadata object found to revise superClass information---not exported?  Making a copy in package ‘.GlobalEnv’
```

Is there any chance to export these classes?

Background: I want to create some S4-methods that just `flatten` `mzID` objects (regardless whether they are single objects or collections). These methods would be exactly the same for both `mzID` and `mzIDCollection` objects. I don't want just copy&paste the method body, e.g.:
```r
### instead of defining two methods ...
setMethod("addIdentificationData", c("MSnExp", "mzID"),
          function(object, id, ...) ...)

setMethod("addIdentificationData", c("MSnExp", "mzIDCollection"),
          function(object, id, ...) ...)

### ... I want to define a class union and define the method just once
setClassUnion("mzIDClasses", members = c("mzID", "mzIDCollection"))
setMethod("addIdentificationData", c("MSnExp", "mzIDClasses"),
          function(object, id, ...) ...)
```

Best wishes,

Sebastian

CC: @lgatto

**Comment by thomasp85** [comment]
The only reason they are not exported was in order to trim the namespace - I didn’t anticipate anyone subclassing these, and didn’t think of your scenario. They’ll be exported from now on…
