### ISSUE TITLE
duplicated generics

### ISSUE THREAD

**Issue by lgatto** [thomasp85/mzID#30]
The [`ProtGenerics`](http://www.bioconductor.org/packages/devel/bioc/html/ProtGenerics.html) package defines generic functions that are used in several proteomics-related packages:

```r
ls('package:ProtGenerics')
 [1] "accessions"    "chromatograms" "database"      "intensity"    
 [5] "ions"          "mass"          "modifications" "mz"           
 [9] "peaks"         "peptides"      "proteins"      "psms"         
[13] "rtime"         "scans"         "spectra"       "tic" 
```

Generics with identical names and different signature, such as `peptides` below, cause errors when `mzID` and, for example `MSnbase` (that uses `ProtGenerics::peptides`) are loaded,

```r
> peptides
standardGeneric for "peptides" defined from package "ProtGenerics"

function (object, ...) 
standardGeneric("peptides")
<environment: 0x4ad4528>
Methods may be defined for arguments: object
Use  showMethods("peptides")  for currently available ones.
```

Would it be possible import `ProtGenerics` and use these generics to avoid these conflicts?

**Comment by thomasp85** [comment]
This is my sleeping on my shift - I honestly thought I moved to ProtGenerics when we had the discussion before last BioC release... I'm currently at home with a concussion so shouldn't even be writing this, let alone try to code, but I'll have a fix once I'm up on my feet again...

**Comment by lgatto** [comment]
I was also convinced you were already using `ProtGenerics`. Anyway, udpate whenever you a fit to do so.

**Comment by thomasp85** [comment]
Fixed in 29f5c608125d6abd517c078be5160cb5ce4ff77d

**Comment by lgatto** [comment]
Thanks. Happy to see you feel better.

**Comment by thomasp85** [comment]
To be honest I was just extremely bored...:-)
