### ISSUE TITLE
mzID returning mapply error

### ISSUE THREAD

**Issue by videlc** [thomasp85/mzID#31]
Hey,

I am currently trying to parse an mzIdentML (".mzid") generated from PeptideShaker but somehow mzID is unable to parse it and returns me this error : 
`Error in mapply(sub, paste("^\\Q", database$accession[hasRightName], "\\E",  :
  zero-length inputs cannot be mixed with those of non-zero length
Calls: mzID ... new -> initialize -> initialize -> mzIDdatabase -> mapply
Execution halted`

Do you have any idea what might be wrong ?

Best regards,
Vivian

**Comment by lgatto** [comment]
Would you mind sharing that file, so that we can have a look into it.

**Comment by videlc** [comment]
Hey Laurent,
Sent you the file link via email.
Best regards,
Vivian

**Comment by videlc** [comment]
Is it possible that it might be due to the non-export of protein sequences when exporting to mzIdentML ?

**Comment by videlc** [comment]
New try with adding protein sequences into mzid file did not solve the problem. returning
```
Error in mapply(sub, paste("^\\Q", database$accession[hasRightName], "\\E",  :
  zero-length inputs cannot be mixed with those of non-zero length
Calls: mzID ... new -> initialize -> initialize -> mzIDdatabase -> mapply
Execution halted
```

**Comment by lgatto** [comment]
I seem to have completely missed this, or did we get to the bottom of this?

**Comment by lgatto** [comment]
Closing, but feel free to reopen if necessary.

**Comment by TessaGillett** [comment]
Hi Laurent,

This was posted a while ago, but I'm getting the same error (though in my case it is returned within a few minutes):

`Error in mapply(sub, paste("^\\Q", database$accession[hasRightName], "\\E",  : 
  zero-length inputs cannot be mixed with those of non-zero length`

Any help would be appreciated! 
Tessa
